version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false

formats: all

submodules:
  include: all
  recursive: true

python:
  install:
    - requirements: doc/requirements-rtd.txt
