name: CI

on: push

jobs:
  build-and-test:
    name: Testing on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: make build directory
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: configure cmake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DBUILD_DOCS=OFF

      - name: build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake --build .

      - name: run tests
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: ctest
